### ISSUE TITLE
[Question] Caching or memoization when possible.

### ISSUE THREAD

**Issue by jrm8005** [himura/twitter-conduit#14]
Is it possible to somehow cache the value returned from an API call? Top-level bindings do not (seem) to accomplish this. For example (withCF is a function borrowed from the samples somewhere) :

memoUser = withCF $ usersShow (ScreenNameParam "someLuser")

Now if you try to apply accessor functions, like userName or userFollowers, those calls cause memoUser to be re-evaluated. Obviously, since there are impure actions going on behind the scenes, memoUser is not technically referentially-transparent, but in certain cases, such as this, replacing memoUser by the value returned by the right-hand-side would be acceptable, and would prevent many applications of other functions from counting against the API limits.

Is there a way to express this with twitter-conduit as is?

**Comment by dzhus** [comment]
If you re-use a pure value returned by an IO action (`memoUser <- ...`), the action will not be re-evaluated.
