### ISSUE TITLE
`searchTweets` is broken

### ISSUE THREAD

**Issue by rdlester** [himura/twitter-conduit#30]
If I try to run a command like:

```haskell
runSearch (login :: TWInfo) = 
  withManager $ \mgr -> call' login mgr (searchTweets "search term")
```

I get an error: `FromJSONError "when expecting a (), encountered Object instead".

Relatedly, `(APIRequest SearchTweets a)` is an instance of `HasMaxIdParam` but `searchTweets` does not have the right signature to be used with `sourceWithMaxId`, as the return type of `searchTweets` is not a list, as required by `sourceWithMaxId`. This isn't a bug persay, but is very annoying.

Also, I can't run the search.hs sample.

**Comment by himura** [comment]
I could not reproduce `FromJSONError ..`, so I need more information.
I guess that the inferred type of `runSearch` function would be `TWInfo -> m ()` because `call'` permits arbitrary types which have FromJSON instance, and `()` have
