### ISSUE TITLE
Worng number of favourites when using showId on a retweet

### ISSUE THREAD

**Issue by lichotapia** [himura/twitter-conduit#38]
I'm using this code:

> twit <- withManager $ \mgr -> call twInfo mgr $ showId (read (head ids))

to get the info on a tweet and this:

>twit ^. statusFavoriteCount

to get the total of favourites.

It works great with original twits. But with retweets, I always get 0 favourites, no matter how many it has.
Couldn't find a way to solve this.

**Comment by himura** [comment]
> twit ^. statusFavoriteCount

It sees the favorite count of not the original tweet but the retweet.
The retweet status have "retweeted_status" field, so you can obtain the favorite count of the original tweet by:

~~~~ {.haskell}
twit ^? statusRetweetedStatus . _Just . statusFavoriteCount
~~~~

**Comment by lichotapia** [comment]
Great!
So sorry, I was using it wrong.
Thank you very much!
