### ISSUE TITLE
Nix package fails, and is marked as broken due to HLint failure. 

### ISSUE THREAD

**Issue by t1lde** [himura/twitter-conduit#79]
I had been unable to build a project of my own using this library with Stack's nix integration, as the nix package fails (and is currently marked as broken!) to build due to the hlint failure. I'm not sure whether it's _supposed_ to cause build failure like this, or whether something else in nixpkgs is causing this...

[Nix package.](https://github.com/NixOS/nixpkgs/blob/e81ec2fa826a99a7459a9fb2eb6c81f9c9c247f6/pkgs/development/haskell-modules/hackage-packages.nix#L264024-L264054) (twitter-conduit is at lines 254024-264054)

```
Test suite hlint: RUNNING...
Web/Twitter/Conduit/Response.hs:2:1-31: Warning: Unused LANGUAGE pragma
Found:
  {-# LANGUAGE DeriveFoldable #-}
Perhaps you should remove it.
Note: Extension DeriveFoldable is implied by DeriveTraversable

Web/Twitter/Conduit/Response.hs:3:1-30: Warning: Unused LANGUAGE pragma
Found:
  {-# LANGUAGE DeriveFunctor #-}
Perhaps you should remove it.
Note: Extension DeriveFunctor is implied by DeriveTraversable

2 hints
Test suite hlint: FAIL
```

**Comment by Montmorency** [comment]
Noticed this as well. I think it's as simple as a white space issue (https://www.snoyman.com/blog/2017/11/future-proofing-test-suites). I was able to build the package in a nix expressions using 
``` 
 config = {
    allowBroken = true;
    packageOverrides = pkgs: rec { 
    haskell = pkgs.haskell // {
        packages = pkgs.haskell.packages // {
          "${compiler}" =
          pkgs.haskell.packages."${compiler}".override {
            overrides = composeExtensionsList [
              generatedOverrides
              (makeOverrides pkgs.haskell.lib.dontCheck   dontCheckPackages  )
            ];
         };
        };};};};
```

where `let dontCheckPackages = [ twitter-conduit]`
